# coding: utf-8

# flake8: noqa

"""
    Flight Booking API

    API for booking and managing flight tickets.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "BookingsApi",
    "FlightsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "BookingCreate",
    "BookingResponse",
    "FlightCreate",
    "FlightResponse",
    "HTTPValidationError",
    "ValidationError",
    "ValidationErrorLocInner",
]

# import apis into sdk package
from openapi_client.api.bookings_api import BookingsApi as BookingsApi
from openapi_client.api.flights_api import FlightsApi as FlightsApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.booking_create import BookingCreate as BookingCreate
from openapi_client.models.booking_response import BookingResponse as BookingResponse
from openapi_client.models.flight_create import FlightCreate as FlightCreate
from openapi_client.models.flight_response import FlightResponse as FlightResponse
from openapi_client.models.http_validation_error import HTTPValidationError as HTTPValidationError
from openapi_client.models.validation_error import ValidationError as ValidationError
from openapi_client.models.validation_error_loc_inner import ValidationErrorLocInner as ValidationErrorLocInner

