# coding: utf-8

"""
    Flight Booking API

    API for booking and managing flight tickets.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.bookings_api import BookingsApi


class TestBookingsApi(unittest.TestCase):
    """BookingsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BookingsApi()

    def tearDown(self) -> None:
        pass

    def test_book_ticket_flights_flight_id_book_post(self) -> None:
        """Test case for book_ticket_flights_flight_id_book_post

        Book Ticket
        """
        pass

    def test_cancel_booking_bookings_booking_id_delete(self) -> None:
        """Test case for cancel_booking_bookings_booking_id_delete

        Cancel Booking
        """
        pass

    def test_get_my_bookings_bookings_me_get(self) -> None:
        """Test case for get_my_bookings_bookings_me_get

        Get My Bookings
        """
        pass


if __name__ == '__main__':
    unittest.main()
