# coding: utf-8

"""
    Flight Booking API

    API for booking and managing flight tickets.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.flights_api import FlightsApi


class TestFlightsApi(unittest.TestCase):
    """FlightsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FlightsApi()

    def tearDown(self) -> None:
        pass

    def test_add_flight_flights_post(self) -> None:
        """Test case for add_flight_flights_post

        Add Flight
        """
        pass

    def test_get_flight_details_flights_flight_id_get(self) -> None:
        """Test case for get_flight_details_flights_flight_id_get

        Get Flight Details
        """
        pass

    def test_list_flights_flights_get(self) -> None:
        """Test case for list_flights_flights_get

        List Flights
        """
        pass


if __name__ == '__main__':
    unittest.main()
