# coding: utf-8

"""
    Flight Booking API

    API for booking and managing flight tickets.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.booking_response import BookingResponse

class TestBookingResponse(unittest.TestCase):
    """BookingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BookingResponse:
        """Test BookingResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BookingResponse`
        """
        model = BookingResponse()
        if include_optional:
            return BookingResponse(
                passenger_name = '',
                passport_number = '',
                id = 56,
                flight_id = 56,
                status = '',
                user_id = 56,
                flight = openapi_client.models.flight_response.FlightResponse(
                    flight_number = '', 
                    airline = '', 
                    departure = '', 
                    destination = '', 
                    departure_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    total_seats = 56, 
                    id = 56, 
                    available_seats = 56, )
            )
        else:
            return BookingResponse(
                passenger_name = '',
                passport_number = '',
                id = 56,
                flight_id = 56,
                status = '',
                user_id = 56,
                flight = openapi_client.models.flight_response.FlightResponse(
                    flight_number = '', 
                    airline = '', 
                    departure = '', 
                    destination = '', 
                    departure_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    total_seats = 56, 
                    id = 56, 
                    available_seats = 56, ),
        )
        """

    def testBookingResponse(self):
        """Test BookingResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
