# coding: utf-8

# flake8: noqa
"""
    Flight Booking API

    API for booking and managing flight tickets.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openapi_client.models.booking_create import BookingCreate
from openapi_client.models.booking_response import BookingResponse
from openapi_client.models.flight_create import FlightCreate
from openapi_client.models.flight_response import FlightResponse
from openapi_client.models.http_validation_error import HTTPValidationError
from openapi_client.models.validation_error import ValidationError
from openapi_client.models.validation_error_loc_inner import ValidationErrorLocInner

