# coding: utf-8

"""
    Flight Booking API

    API for booking and managing flight tickets.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from openapi_client.models.flight_response import FlightResponse
from typing import Optional, Set
from typing_extensions import Self

class BookingResponse(BaseModel):
    """
    BookingResponse
    """ # noqa: E501
    passenger_name: StrictStr
    passport_number: Annotated[str, Field(strict=True)]
    id: StrictInt
    flight_id: StrictInt
    status: StrictStr
    user_id: StrictInt
    flight: FlightResponse
    __properties: ClassVar[List[str]] = ["passenger_name", "passport_number", "id", "flight_id", "status", "user_id", "flight"]

    @field_validator('passport_number')
    def passport_number_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[A-Za-z]{1,3}[0-9]{6,9}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z]{1,3}[0-9]{6,9}$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BookingResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of flight
        if self.flight:
            _dict['flight'] = self.flight.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BookingResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "passenger_name": obj.get("passenger_name"),
            "passport_number": obj.get("passport_number"),
            "id": obj.get("id"),
            "flight_id": obj.get("flight_id"),
            "status": obj.get("status"),
            "user_id": obj.get("user_id"),
            "flight": FlightResponse.from_dict(obj["flight"]) if obj.get("flight") is not None else None
        })
        return _obj


